### ISSUE TITLE
Add these hidden particles

### ISSUE THREAD

**Issue by ShrooToo** [TurboBiscuit/smleaks#4]
4 unused particles to add to the website:
https://www.youtube.com/watch?v=dqVTn9LYx2M

**Comment by TurboBiscuit** [comment]
@ShrooToo what are the name of these particles btw?

**Comment by ShrooToo** [comment]
Sorry I took so long to reply, the names are "Orientation", "Placeholder 1", "Placeholder 2", and "Placeholder 3" respectively.
